### ISSUE TITLE
No module named 'submodules.patched_clip'

### ISSUE THREAD

**Issue by maurock** [vuer-ai/feature-splatting-inria#2]
Hi, thanks for this great repository!

I have followed the script and the Training works correctly. However, in the Rendering section, once I run:

`python render.py -m output/garden_table -s feat_data/garden_table --camera_slerp_list 0 1 --with_feat --clip_feat --text_query 'a vase with flowers' --step_size 10`

I encounter the following error:
```
File "feature-splatting-inria/featsplat_editor/clip_segmenter.py", line 6, in <module>
    from submodules.patched_clip.patched_clip.patched_clip import CLIP_args, load_clip
ModuleNotFoundError: No module named 'submodules.patched_clip'
```

Could you please let me know how I can address this issue?
Thank you

**Comment by RogerQi** [comment]
That's an issue on my end. patched_clip was an obsolete module that I used when I developed the codebase and later removed during the release for cleanness. I will push a fix

**Comment by RogerQi** [comment]
I just pushed the fix to the main branch. Tested on a fresh conda env and I think the issue has been fixed.

I am closing this issue for now. Feel free to open a new issue / follow up if you have further question!
